// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // For CLI commands (migrate/push), use the DIRECT connection (Port 5432)
    url: env("DIRECT_URL"),
  },
  // We explicitly turn off migration logic for Sprint 1 purely to keep it simple, 
  // but you can leave this section out if you want standard behavior.
});